Feature/import protocol upload
complexdatacollective/Fresco pull request #7
Opened 2023-08-30 10:13 UTC by jabu404

Draft PR

2023-09-05 20:46 UTC, buckhalt requested changes
Overall, this is looking really great!

I think the UI of the upload status, loading states, and error/success messaging is solid. I have a few ideas for improving the UI of the import action where the user provides the file to import:
-  Adding a border to the area which will accept a file to be dropped to make the action more clear to the user.
- Have the existing Import Protocol button open a modal, similar to the existing component you created, which has the drop zone and button for opening local files to select.
- If possible, only make the button for browsing clickable, instead of the entire drop zone.

A rough example of what this could look like:
![Screenshot 2023-09-05 at 12 55 58 PM](https://github.com/complexdatacollective/Fresco/assets/75645391/4a4181be-3543-4eaa-b4b2-bd42230e4ae7)

2023-09-06 07:19 UTC, jabu404 commented on app/(main)/_actions/importProtocol.ts
> +  return {
Yeah this is just mocking validation, validation will be worked on in a separate pr

2023-09-06 12:19 UTC, jthrilly commented on app/(main)/_actions/importProtocol.ts
> +} from '../../../lib/shared-consts';
@buckhalt - yes, completely agree. 

@jabu404 - could you add that here?

2023-09-06 12:27 UTC, jthrilly reviewed
I think UI wise this is really great. You've done a brilliant job with the messaging and the progress bar.

Aside from the alias and the eslint rule to enforce it, the only other small UI nitpick is setting the correct cursor for the button (currently shows text select rather than pointer). 

I do agree with Caden about the dropzone UI state, but I know that styling that isn't a priority here. Perhaps just make the drop area a full width rectangle with some padding, and the button centered, and maybe add a border?

2023-09-07 08:28 UTC, jthrilly approved these changes
Looking great to me!

There are some changes in my user auth PR that might not merge cleanly with this, so I would prefer we get this in now so that I can rebase my work before I get too far into it.

Assuming you are happy with it, I am going to go ahead and merge now based on that. Any future changes can happen in a subsequent branch.

2023-09-07 08:32 UTC, merged